
version: "3"
services:
  employee-container:
    image: employeedemo
    ports:
      - 8090:8090
    environment:
      - spring.datasource.url:'jdbc:mysql://emp-mysql:3306/'
    networks:
      - employeedemo-mysql
    depends_on:
      - emp-mysql
 
  emp-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: emp_mysql
    environment:
      - MYSQL_ROOT_PASSWORD:password
      - MYSQL_USER:root
      - MYSQL_PASSWORD:password
      - MYSQL_DATABASE:employee_db
    ports:
      - 3306:3306
    networks:
      - employeedemo-mysql
    

networks:
  employeedemo-mysql:
  
=======
version: '3'

services:
    database:
        image: mysql
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: employee_db
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306
        volumes:
            - employee_db:/var/lib/mysql
        networks:
            - backendNetwork
    employee_backend:
        image: openjdk:8-jdk-alpine
        container_name: employee_backend_app
        ports:
            - 8000:8080
        depends_on:
            - database
        volumes:
            - ./target/EmployeeDemo-0.0.1-SNAPSHOT.jar:/app.jar
        command: ["java", "-jar", "app.jar"]
        networks:
            - backendNetwork
volumes:
    employee_db:

networks:
    backendNetwork:
    frontendNetwork:
