version: '3'

services:
    database:
        image: mysql
        container_name: database
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: dockerAngularSpringDatabase
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        ports:
            - 3306:3306
        volumes:
            - /var/lib/mysql
