version: "3"
services:
  employee-container:
    image: employeedemo
    ports:
      - 8090:8090
    environment:
      - spring.datasource.url:'jdbc:mysql://emp-mysql:3306/'
    networks:
      - employeedemo-mysql
    depends_on:
      - emp-mysql
 
  emp-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: emp_mysql
    environment:
      - MYSQL_ROOT_PASSWORD:password
      - MYSQL_USER:root
      - MYSQL_PASSWORD:password
      - MYSQL_DATABASE:employee_db
    ports:
      - 3306:3306
    networks:
      - employeedemo-mysql
    

networks:
  employeedemo-mysql:
  